spring.application.name=mcpserverstdio

# ENABLE COLOR ON CONSOLE LOGS
spring.output.ansi.enabled=always

# This MCP-SERVER SHOULD RUN AS A NORMAL WEB SERVER
server.port=8090

spring.datasource.url=jdbc:h2:file:~/chatmemory-db;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Test
spring.datasource.password=Test
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

