spring.application.name=spring-ai

# enable color output in logs
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
#spring.output.ansi.enabled=ALWAYS

spring.ai.openai.api-key=${OPENAI_API_KEY}

# LOGGING LEVEL FOR ADVISOR PACKAGE
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:~/chatmemory-db;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Test
spring.datasource.password=Test

# Always update the database schema on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable SQL-Syntax highlighting in the console
spring.jpa.properties.hibernate.highlight_sql=true

spring.h2.console.enabled=true
#spring.ai.openai.chat.options.model=gpt-5.4
#spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.chat.memory.repository.jdbc.initialize-schema=always
spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

spring.docker.compose.stop.command=down

# CONSIDER DOCKER COMPOSE IN TESTS
spring.docker.compose.skip.in-tests=false

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=eazybytes
