spring.application.name=spring-ai

logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
# enable color output on standard logs
#spring.output.ansi.enabled=ALWAYS

spring.ai.openai.api-key=${OPENAI_API_KEY}

# LOGGING LEVEL FOR ADVISOR PACKAGE
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# New: Sec4_Chap48
spring.datasource.url=jdbc:h2:file:~/chatmemory-ai-1.1.4-db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Test
spring.datasource.password=Test

# New: Sec4_Chap48
# Spring AI 1.1.4 Chat Memory Repository JDBC Configuration
# spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# New: Sec4_Chap48
# No more need to specify the schema location as
# Spring AI 1.1.4 will auto-detect it from the classpath
#spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

# New: Sec5_Chap54
spring.docker.compose.stop.command=down

# New: Sec5_Chap54
spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=eazybytes

# CONSIDER DOCKER COMPOSE IN TESTS
spring.docker.compose.skip.in-tests=false
