spring.application.name=multimodel
# enable colour on console
spring.output.ansi.enabled=always

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.ollama.chat.options.model=llama3.2:1b

# disable the auto-configuration of the spring.ai.chat.client,
# we will create our own bean for it
spring.ai.chat.client.enabled=false