spring.application.name=openai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

spring.ai.model.chat=bedrock-converse
#spring.ai.bedrock.converse.chat.options.model=eu.anthropic.claude-haiku-4-5-20251001-v1:0
# Works but behaves differently than the one above
spring.ai.bedrock.converse.chat.options.model=eu.anthropic.claude-sonnet-4-6
#spring.ai.bedrock.converse.chat.options.model=eu.anthropic.claude-opus-4-6-v1
spring.ai.bedrock.aws.region=eu-central-1

# config proposed by AWS AI assistant
# Hallucination is not working.
#spring.ai.aws.region=eu-central-1

# config proposed by GitHub Copilot
# Hallucination is not working.
#spring.ai.aws.credentials.profile-name=default
