spring.application.name=openai
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

#spring.ai.bedrock.aws.region=AWS_REGION
#spring.ai.bedrock.aws.access-key=ACCESSKEY
#spring.ai.bedrock.aws.secret-key=SECRETKEY


spring.ai.model.chat=bedrock-converse
spring.ai.bedrock.converse.chat.options.model=eu.anthropic.claude-haiku-4-5-20251001-v1:0
spring.ai.aws.credentials.profile-name=default

spring.ai.aws.region=eu-central-1
# config proposed by AWS Bedrock, incredible!!!!!
#spring.ai.aws.region=eu-central-1

