spring.application.name=spring-ai

# ENABLE COLOR OUTPUT IN LOGS
logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
#spring.output.ansi.enabled=ALWAYS

spring.ai.openai.api-key=${OPENAI_API_KEY}
# GPT-5.5 doesn't accept the default temperature of 0.7!!!!
spring.ai.openai.chat.options.model=gpt-5.4-mini

# LOGGING LEVEL FOR ADVISOR PACKAGE
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.datasource.url=jdbc:h2:file:~/chatmemory-ai-1.1.4-db;AUTO_SERVER=true
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=Test
spring.datasource.password=${TESTER_PASSWORD}

# ALWAYS UPDATE THE DATABASE SCHEMA ON STARTUP
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Enable SQL-Syntax highlighting in the console
spring.jpa.properties.hibernate.highlight_sql=true

spring.h2.console.enabled=true
#spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# No more need to specify the schema location as
# Spring AI 1.1.4 will auto-detect it from the classpath
#spring.ai.chat.memory.repository.jdbc.schema=classpath:/schema/schema-h2db.sql

spring.docker.compose.stop.command=down

# CONSIDER DOCKER COMPOSE IN TESTS
spring.docker.compose.skip.in-tests=false

spring.ai.vectorstore.qdrant.initialize-schema=true
spring.ai.vectorstore.qdrant.host=localhost
spring.ai.vectorstore.qdrant.port=6334
spring.ai.vectorstore.qdrant.collection-name=eazybytes

# CONTROLS WHICH ACTUATOR ENDPOINTS ARE EXPOSED OVER HTTP
# (here: health, metrics, prometheus)
management.endpoints.web.exposure.include=health,metrics,prometheus

# OPENTELEMETRY CONFIGURATION
opentelemetry.exporter.otlp.endpoint=http://localhost:4317

# CONTROLS WHAT FRACTION OF REQUESTS IS RECORDED
# BY THE APP'S TRACING SYSTEM. (HERE 1.0 = 100%, 0.0 = 0%)
management.tracing.sampling.probability=1.0