spring.application.name=mcpclient

# Enable ANSI colors in the console output
spring.output.ansi.enabled=ALWAYS
#logging.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

# Set logging level for the AI chat client advisor to DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

spring.ai.openai.api-key=${OPENAI_API_KEY}

